[workspace]
resolver = "3"
members = ["bin/db", "lib/models"]

[workspace.dependencies]
arma-rs = { version = "^1", features = ["uuid", "serde_json"] }
serde = "^1"
serde_json = "^1"
tokio = "^1"
uuid = "^1"