name = "forge-server"
author = "IDSolutions"
prefix = "forge_server"
mainprefix = "forge"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_forge_server.png",
    "logo_forge_server_over.png",
    "logo_forge_server_ca.paa",
    "logo_forge_server_over_ca.paa",
    "LICENSE.md",
    "README.md"
]
exclude = []

[properties]
author = "IDSolutions"
